version: '2.1'

services:
  db:
    image: postgres
    build:
      context: ./db
      dockerfile: Dockerfile
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=santadb
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
    volumes:
      - db_data:/var/lib/postgresql/data/

  r:
    image: shiny-santa
    build: .
    environment:
      - DATABASE_URL=postgres://postgres_user:postgres_pass@db:5432/santadb
    ports:
      - 3838:3838
    depends_on:
      - db

volumes:
  db_data:
